server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://app-wallet-learning.eastus.cloudapp.azure.com:8761/eureka

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: contas
          uri: lb://CONTA-SERVICE
          predicates:
            - Path=/contas/**, /agencias/**, /transacoes/**, /contas/v2/api-docs/**
        - id: contas
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/usuarios/**

swagger:
  config:
    refreshrate: 5000000