server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:

  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: contas
          uri: lb://CONTA-SERVICE
          predicates:
            - Path=/contas/**, /agencias/**, /transacoes/**, /contas/v2/api-docs/**

swagger:
  config:
    refreshrate: 5000000